version: '3.3'

services:

  checkmk:
    image: checkmk/check-mk-raw
    container_name: checkmk    
    restart: unless-stopped
    ulimits:
      nofile: 1024
    ports:
      - "8200:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./monitoring:/omd/sites

      